# Example exs2

Analysis of one dimensional heat flow.

In [1]:
import numpy as np
import calfem.core as cfc

## Topology matrix Edof

In [2]:
Edof = np.array([
    [1,2],
    [2,3],
    [3,4],
    [4,5],
    [5,6]
])

## Stiffness matrix K and vector f

In [3]:
K = np.mat(np.zeros((6,6)))
f = np.mat(np.zeros((6,1)))
f[3] = 10.0

## Element properties

In [4]:
ep1 = 25.0
ep2 = 24.3
ep3 = 0.4
ep4 = 17.0
ep5 = 7.7

## Element stiffness matrices

In [5]:
Ke1 = cfc.spring1e(ep1)
Ke2 = cfc.spring1e(ep2)
Ke3 = cfc.spring1e(ep3)
Ke4 = cfc.spring1e(ep4)
Ke5 = cfc.spring1e(ep5)

## Assemble Ke into K

In [6]:
cfc.assem(Edof[0,:], K, Ke1)
cfc.assem(Edof[1,:], K, Ke2) 
cfc.assem(Edof[2,:], K, Ke3)
cfc.assem(Edof[3,:], K, Ke4)
cfc.assem(Edof[4,:], K, Ke5)

print("Stiffness matrix K:")
print(K)

Stiffness matrix K:
[[ 25.  -25.    0.    0.    0.    0. ]
 [-25.   49.3 -24.3   0.    0.    0. ]
 [  0.  -24.3  24.7  -0.4   0.    0. ]
 [  0.    0.   -0.4  17.4 -17.    0. ]
 [  0.    0.    0.  -17.   24.7  -7.7]
 [  0.    0.    0.    0.   -7.7   7.7]]


## Solve the system of equations

In [7]:
bc = np.array([1,6])
bcVal = np.array([-17.0, 20.0])
a,r = cfc.solveq(K, f, bc, bcVal)

print("Displacements a:")
print(a)

print("Reaction forces r:")
print(r)

Displacements a:
[[-17.        ]
 [-16.43842455]
 [-15.86067203]
 [ 19.23779344]
 [ 19.47540439]
 [ 20.        ]]
Reaction forces r:
[[-1.40393862e+01]
 [-5.68434189e-14]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 4.03938619e+00]]
